### ISSUE TITLE
belongsTo should exception if relation mae doesnt exists 

### ISSUE THREAD

**Issue by ItaloBC** [Larawiz/Larawiz#23]
https://github.com/Larawiz/Larawiz/blob/master/src/Parsers/Database/Pipes/ParseModelBelongToColumnRelation.php#L46

If the model doesn't exists (because it's null), it should throw an Exception saying that.

**Comment by DarkGhostHunter** [comment]
https://github.com/Larawiz/Larawiz/commit/799f6821b25201d90fb335c5272740e062bdab92
